# This is a basic workflow to help you get started with Actions

name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
    
      - name: Cache
        uses: actions/cache@v2.1.4
        with:
          path: |
           ~/.gradle/caches/modules-*
           ~/.gradle/caches/jars-*
           ~/.gradle/caches/build-cache-*
           ~/.gradle/*
           ./*/build/*
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties','./*/build/*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
    
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Gradle build
        run: ./gradlew build
  
  test:
    name: Test
    needs: build
    runs-on: ubuntu-20.04
    steps:
     
     - name: Unit tests
       uses: ReactiveCircus/android-emulator-runner@v2.16.0
       with:
          api-level: 30
          script: ./gradlew test
       
     - name : Instrumented Tests
       uses: ReactiveCircus/android-emulator-runner@v2.16.0
       with:
        api-level: 29
        script: ./gradlew connectedCheck
  
  
  
  
