# This is a basic workflow to help you get started with Actions

name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-20.04
    
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Cache Android SDK
        uses: actions/cache@v2.1.4
        with:
          path: |
           /usr/local/lib/android/*
          key: ${{ runner.os }}-android-sdk-${{ hashFiles('/usr/local/lib/android/*') }}
          restore-keys: |
            ${{ runner.os }}-android-sdk-
            
      - name: Unit tests
        uses: ReactiveCircus/android-emulator-runner@v2.16.0
        with:
           api-level: 29
           script: ./gradlew test
       
      - name : Instrumented Tests
        uses: ReactiveCircus/android-emulator-runner@v2.16.0
        with:
         api-level: 29
         script: ./gradlew connectedCheck
  

  
 
